version: '3.9'
services:
  database-1.chwvkxbwkqbg.ap-northeast-1.rds.amazonaws.com:
    image: mysql
    container_name: database
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
    expose:
      - 3306
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - react-django
  web-app:
    image: web-app
    build: web-app
    container_name: web-app
    restart: always
    ports:
      - 80:80
    environment:
      - DB_USER=test
      - DB_PASSWORD=password
      - DB_HOST=database-1.chwvkxbwkqbg.ap-northeast-1.rds.amazonaws.com
    networks:
      - react-django
networks:
  react-django:
    name: react-django
