version: '3.9'
services:
  application:
    image: tuimac/application
    container_name: application
    restart: always
    expose:
      - 8000
    networks:
      - react-django
  web:
    image: tuimac/web
    container_name: web
    restart: always
    ports:
      - 80:80
    networks:
      - react-django
networks:
  react-django:
    name: react-django
